Auth api
Scuudu-Labs/Tranzakt_Dashboard_v2 pull request #5
Opened 2023-10-26 08:17 UTC by Ifenna-Monanu

2023-10-26 10:55 UTC, Dverybest requested changes
why did you switch from yarn to npm?

2023-10-26 10:55 UTC, Dverybest commented on src/components/nav/LeftNav.tsx
> +            <MdOutlineDashboard style={{color: `${pathname === '/dashboard' ? "#fff" : '#A1A1A1'}`}} />
Why not create a theme file and keep all the colors there

2023-10-26 10:55 UTC, Dverybest commented on src/config/index.ts
> +// import {config} from 'dotenv'
what is happening here

2023-10-26 10:55 UTC, Dverybest commented on src/redux/api/auth/index.ts
> +              ) => {
these repetitions are unnecessary, there are better ways to do this

2023-10-26 10:55 UTC, Dverybest commented on src/redux/getPreloadedState.ts
> +        }
rewrite this  to be neat

2023-10-26 10:55 UTC, Dverybest commented on src/redux/store.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
why this?

2023-10-26 10:55 UTC, Dverybest commented on src/redux/store.ts
> +export type Store = ReturnType<any>;
Remove type any

2023-10-26 11:08 UTC, Ifenna-Monanu commented on src/components/Input/PasswordInput.tsx
> +import { ReactComponent as HideSvg } from "../../assets/icons/hide.svg";
This is done in the previous PR

2023-10-26 22:37 UTC, Dverybest requested changes

2023-10-26 22:37 UTC, Dverybest commented on .env
> +REACT_APP_BASE_URL = https://api.tranzakt.app/docs/api/v1
@Ifenna-Monanu this is still not fixed

2023-10-28 19:21 UTC, Dverybest commented on .env
> +REACT_APP_BASE_URL = https://api.tranzakt.app/docs/api/v1
this is not resolved yet

2023-10-28 23:07 UTC, Ifenna-Monanu commented on .env
> +REACT_APP_BASE_URL = https://api.tranzakt.app/docs/api/v1
I have fixed it already thanks, please recheck

2023-10-30 08:04 UTC, Dverybest approved these changes

2023-10-30 08:04 UTC, merged